fix: remove asterisks from comments
cla-assistant/github-action pull request #76
Opened 2021-03-10 21:43 UTC by mattrosno

This pull request fixes two issues.

1) It's unclear if you're supposed to include the `***` or not surrounding the confirmation text. If you include it, it looks like broken markdown formatting.

2) The DCO option has an extra space between the confirmation text and the ending `***`.

Both are addressed by removing the `***`. Here is a screenshot before the fix to show the as-is:

![image](https://user-images.githubusercontent.com/1691245/110701834-4a458380-81b7-11eb-938f-19bd2a032194.png)

2021-03-10 21:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cla-assistant/github-action?pullRequest=76) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cla-assistant/github-action?pullRequest=76) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cla-assistant/github-action?pullRequest=76) it.</sub>

2021-03-10 22:32 UTC, mattrosno commented
This PR demonstrates how the asterisks fail the action: https://github.com/carbon-design-system/carbon-dco/pull/4

Where this PR worked with the asterisks not included: https://github.com/carbon-design-system/carbon-dco/pull/7

2021-03-11 11:26 UTC, ibakshay commented
thanks a lot for your contribution :)

2021-03-11 11:34 UTC, ibakshay requested changes

2021-03-11 11:34 UTC, ibakshay commented on src/pullrequest/pullRequestCommentContent.ts
> -   ***${input.getCustomPrSignComment() || "I have read the DCO Document and I hereby sign the DCO"} ***
It is great that you have pointed the bug. 
We can also solve this problem by just removing the space before the ***.
three asteriks will make the markdown text to Bold and italic. 
Example: ***Italic text***

2021-03-11 11:38 UTC, ibakshay commented on src/pullrequest/pullRequestCommentContent.ts
> -   ***${input.getCustomPrSignComment() || "I have read the DCO Document and I hereby sign the DCO"} ***
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2021-03-11 11:39 UTC, ibakshay commented on src/pullrequest/pullRequestCommentContent.ts
> -   ***${input.getCustomPrSignComment() || "I have read the DCO Document and I hereby sign the DCO"} ***
this is how the text will look then :)

2021-03-11 17:02 UTC, mattrosno commented on src/pullrequest/pullRequestCommentContent.ts
> -   ***${input.getCustomPrSignComment() || "I have read the DCO Document and I hereby sign the DCO"} ***
Fixed!

2021-03-11 17:04 UTC, mattrosno commented
@ibakshay this PR now only removes that space to fix markdown formatting. Thank you for your review!

2021-03-11 22:32 UTC, merged